export interface AppSettings {
  autoGenerateEnabled: boolean;
  autoGenerateTime: string; // HH:MM format, e.g., "21:00"
  lastAutoGenerateDate: string | null; // ISO date YYYY-MM-DD
}

const SETTINGS_KEY = 'dogtracer_app_settings';

const DEFAULT_SETTINGS: AppSettings = {
  autoGenerateEnabled: false,
  autoGenerateTime: '21:00',
  lastAutoGenerateDate: null,
};

export function getSettings(): AppSettings {
  if (typeof window === 'undefined') return DEFAULT_SETTINGS;
  const stored = localStorage.getItem(SETTINGS_KEY);
  if (!stored) return DEFAULT_SETTINGS;
  try {
    return { ...DEFAULT_SETTINGS, ...JSON.parse(stored) };
  } catch {
    return DEFAULT_SETTINGS;
  }
}

export function saveSettings(settings: Partial<AppSettings>): void {
  const current = getSettings();
  localStorage.setItem(SETTINGS_KEY, JSON.stringify({ ...current, ...settings }));
}

export function setAutoGenerateEnabled(enabled: boolean): void {
  saveSettings({ autoGenerateEnabled: enabled });
}

export function setAutoGenerateTime(time: string): void {
  saveSettings({ autoGenerateTime: time });
}

export function markAutoGenerateRun(date: Date): void {
  saveSettings({ lastAutoGenerateDate: date.toISOString().split('T')[0] });
}

export function shouldAutoGenerate(): boolean {
  const settings = getSettings();
  if (!settings.autoGenerateEnabled) return false;

  const now = new Date();
  const todayStr = now.toISOString().split('T')[0];
  
  // Already generated today
  if (settings.lastAutoGenerateDate === todayStr) return false;

  const [hours, minutes] = settings.autoGenerateTime.split(':').map(Number);
  const currentHour = now.getHours();
  const currentMinute = now.getMinutes();

  // Check if current time is past the configured auto-generate time
  if (currentHour > hours || (currentHour === hours && currentMinute >= minutes)) {
    return true;
  }

  return false;
}
